//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaBrowser.Theater.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaBrowser.Theater.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @InstallAction_DoNotInstall.
        /// </summary>
        public static string InstallAction_DoNotInstall {
            get {
                return ResourceManager.GetString("InstallAction_DoNotInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @InstallAction_Install.
        /// </summary>
        public static string InstallAction_Install {
            get {
                return ResourceManager.GetString("InstallAction_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @InstallAction_Update.
        /// </summary>
        public static string InstallAction_Update {
            get {
                return ResourceManager.GetString("InstallAction_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NextActionType_Finish.
        /// </summary>
        public static string NextActionType_Finish {
            get {
                return ResourceManager.GetString("NextActionType_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NextActionType_Next.
        /// </summary>
        public static string NextActionType_Next {
            get {
                return ResourceManager.GetString("NextActionType_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_CancelButton.
        /// </summary>
        public static string SetupWizard_CancelButton {
            get {
                return ResourceManager.GetString("SetupWizard_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_CancelConfirmMessage.
        /// </summary>
        public static string SetupWizard_CancelConfirmMessage {
            get {
                return ResourceManager.GetString("SetupWizard_CancelConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_CancelConfirmTitle.
        /// </summary>
        public static string SetupWizard_CancelConfirmTitle {
            get {
                return ResourceManager.GetString("SetupWizard_CancelConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_Introduction_Content.
        /// </summary>
        public static string SetupWizard_Introduction_Content {
            get {
                return ResourceManager.GetString("SetupWizard_Introduction_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_Introduction_Title.
        /// </summary>
        public static string SetupWizard_Introduction_Title {
            get {
                return ResourceManager.GetString("SetupWizard_Introduction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_Prerequisites_AlreadyInstalled.
        /// </summary>
        public static string SetupWizard_Prerequisites_AlreadyInstalled {
            get {
                return ResourceManager.GetString("SetupWizard_Prerequisites_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_Prerequisites_Content.
        /// </summary>
        public static string SetupWizard_Prerequisites_Content {
            get {
                return ResourceManager.GetString("SetupWizard_Prerequisites_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_Prerequisites_Install.
        /// </summary>
        public static string SetupWizard_Prerequisites_Install {
            get {
                return ResourceManager.GetString("SetupWizard_Prerequisites_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_Prerequisites_Title.
        /// </summary>
        public static string SetupWizard_Prerequisites_Title {
            get {
                return ResourceManager.GetString("SetupWizard_Prerequisites_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_PrerequisitesInstallation_Failed.
        /// </summary>
        public static string SetupWizard_PrerequisitesInstallation_Failed {
            get {
                return ResourceManager.GetString("SetupWizard_PrerequisitesInstallation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_PrerequisitesInstallation_Installed.
        /// </summary>
        public static string SetupWizard_PrerequisitesInstallation_Installed {
            get {
                return ResourceManager.GetString("SetupWizard_PrerequisitesInstallation_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_PrerequisitesInstallation_ManualRequired.
        /// </summary>
        public static string SetupWizard_PrerequisitesInstallation_ManualRequired {
            get {
                return ResourceManager.GetString("SetupWizard_PrerequisitesInstallation_ManualRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_PrerequisitesInstallation_Title.
        /// </summary>
        public static string SetupWizard_PrerequisitesInstallation_Title {
            get {
                return ResourceManager.GetString("SetupWizard_PrerequisitesInstallation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_PreviousButton.
        /// </summary>
        public static string SetupWizard_PreviousButton {
            get {
                return ResourceManager.GetString("SetupWizard_PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_ServerDetails_AddessLabel.
        /// </summary>
        public static string SetupWizard_ServerDetails_AddressLabel {
            get {
                return ResourceManager.GetString("SetupWizard_ServerDetails_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_ServerDetails_ConnectionFailedError.
        /// </summary>
        public static string SetupWizard_ServerDetails_ConnectionFailedError {
            get {
                return ResourceManager.GetString("SetupWizard_ServerDetails_ConnectionFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_ServerDetails_Content.
        /// </summary>
        public static string SetupWizard_ServerDetails_Content {
            get {
                return ResourceManager.GetString("SetupWizard_ServerDetails_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_ServerDetails_ServerDownloadLinkText.
        /// </summary>
        public static string SetupWizard_ServerDetails_ServerDownloadLinkText {
            get {
                return ResourceManager.GetString("SetupWizard_ServerDetails_ServerDownloadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SetupWizard_ServerDetails_Title.
        /// </summary>
        public static string SetupWizard_ServerDetails_Title {
            get {
                return ResourceManager.GetString("SetupWizard_ServerDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @StartupWizard_Prerequisites_Searching.
        /// </summary>
        public static string StartupWizard_Prerequisites_Searching {
            get {
                return ResourceManager.GetString("StartupWizard_Prerequisites_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @StartupWizard_Title.
        /// </summary>
        public static string StartupWizard_Title {
            get {
                return ResourceManager.GetString("StartupWizard_Title", resourceCulture);
            }
        }
    }
}
