//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaBrowser.Theater.DefaultTheme.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaBrowser.Theater.DefaultTheme.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Core_ExitApplicationCommand.
        /// </summary>
        internal static string Core_ExitApplicationCommand {
            get {
                return ResourceManager.GetString("Core_ExitApplicationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Core_RestartCommand.
        /// </summary>
        internal static string Core_RestartCommand {
            get {
                return ResourceManager.GetString("Core_RestartCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Core_ShutdownCommand.
        /// </summary>
        internal static string Core_ShutdownCommand {
            get {
                return ResourceManager.GetString("Core_ShutdownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Core_SleepCommand.
        /// </summary>
        internal static string Core_SleepCommand {
            get {
                return ResourceManager.GetString("Core_SleepCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_LatestEpisodes_Title.
        /// </summary>
        internal static string Home_LatestEpisodes_Title {
            get {
                return ResourceManager.GetString("Home_LatestEpisodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_LatestMovies_Title.
        /// </summary>
        internal static string Home_LatestMovies_Title {
            get {
                return ResourceManager.GetString("Home_LatestMovies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_LatestTrailers_Title.
        /// </summary>
        internal static string Home_LatestTrailers_Title {
            get {
                return ResourceManager.GetString("Home_LatestTrailers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_MovieSpotlight_Title.
        /// </summary>
        internal static string Home_MovieSpotlight_Title {
            get {
                return ResourceManager.GetString("Home_MovieSpotlight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_MoviesSectionTitle.
        /// </summary>
        internal static string Home_MoviesSectionTitle {
            get {
                return ResourceManager.GetString("Home_MoviesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_ResumeEpisodes_Title.
        /// </summary>
        internal static string Home_ResumeEpisodes_Title {
            get {
                return ResourceManager.GetString("Home_ResumeEpisodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_TVSectionTitle.
        /// </summary>
        internal static string Home_TVSectionTitle {
            get {
                return ResourceManager.GetString("Home_TVSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Home_TvSpotlight_Title.
        /// </summary>
        internal static string Home_TvSpotlight_Title {
            get {
                return ResourceManager.GetString("Home_TvSpotlight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Login_InvalidCredentialsError.
        /// </summary>
        internal static string Login_InvalidCredentialsError {
            get {
                return ResourceManager.GetString("Login_InvalidCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Login_Login.
        /// </summary>
        internal static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Login_Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Login_RememerMe.
        /// </summary>
        internal static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Login_Title.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Login_Username.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Search_SearchCommand.
        /// </summary>
        internal static string Search_SearchCommand {
            get {
                return ResourceManager.GetString("Search_SearchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Sidebar_AddUserCommand.
        /// </summary>
        internal static string Sidebar_AddUserCommand {
            get {
                return ResourceManager.GetString("Sidebar_AddUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Sidebar_LogoutCommand.
        /// </summary>
        internal static string Sidebar_LogoutCommand {
            get {
                return ResourceManager.GetString("Sidebar_LogoutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Sidebar_OpenCommand.
        /// </summary>
        internal static string Sidebar_OpenCommand {
            get {
                return ResourceManager.GetString("Sidebar_OpenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Theme_Name.
        /// </summary>
        internal static string Theme_Name {
            get {
                return ResourceManager.GetString("Theme_Name", resourceCulture);
            }
        }
    }
}
